-- No global/shared categories in V2: each user gets their OWN editable copy of
-- the default categories via the public.handle_new_user() trigger on signup
-- (see 20240101000000_initial_schema.sql). This file is intentionally empty.
